### ISSUE TITLE
Design question: why both instead of apply

### ISSUE THREAD

**Issue by texastoland** [janestreet/ppx_let#9]
I was trying to understand how `and` in `ppx_let` relates to `ApplicativeDo` in Haskell. First I derived `both` from `bind`:

```ml
let both ta tb =
  ta >>= fun a ->
  tb >>= fun b ->
  return (a, b)
```

Of course that would be sequential so I looked at `apply`:

```ml
let both ta tb =
  let mkTuple a b = (a, b) in
  pure mkTuple <*> ta <*> tb
```

This is essentially what's done in Base where `let both ta tb = map2 ta tb ~f:mkTuple` and `map2` is `liftA2` in Haskell:
https://github.com/janestreet/base/blob/b6d35e2fc402b60918391da53fa644545a2ad4b8/src/applicative.ml#L47

Without lazy evaluation `apply` is still sequential. I guess any concurrent implementation needs a thunk like in `Async.Deferred1`:
https://github.com/janestreet/async_kernel/blob/8e74f62594bf0b3b4c848fe1c5546ecc51195dff/src/deferred1.ml#L67-L70

With the thunk both `apply` and `both` could concurrently evaluate closures all the way down the call tree. Would `apply` not desugar without intermediate tuples (and fewer closures if `both` were derived from `apply`)?

```ml
(* from readme *)
let%bind P1 = M1 and P2 = M2 and P3 = M3 and P4 = M4 in E

(* using apply *)
let x1 = M1 and x2 = M2 and x3 = M3 and x4 = M4 in
bind
  (apply (apply (apply (apply (pure
  (fun (P1, P2, P3, P4) -> E)) x1) x2) x3) x4)
 
(* using both *)
let x1 = M1 and x2 = M2 and x3 = M3 and x4 = M4 in
bind
  (both x1 (both x2 (both x3 x4)))
  ~f:(fun (P1, (P2, (P3, P4))) -> E)
```

Just curious why `both` was chosen. On one hand it's easier to understand. On the other I imagine any monad would already have `apply`.

**Comment by lpw25** [comment]
The apply translation you give there is not correct. For `let%bind` it would actually be:

```ocaml
let x1 = M1 and x2 = M2 and x3 = M3 and x4 = M4 in
join (apply (apply (apply (apply
  (pure (fun P1 P2 P3 P4 -> E))
  x1) x2) x3) x4)
```

whilst for `let%map` it would be:

```ocaml
let x1 = M1 and x2 = M2 and x3 = M3 and x4 = M4 in
apply (apply (apply (apply
  (pure (fun P1 P2 P3 P4 -> E))
  x1) x2) x3) x4
```

Note that they require different translations, and that `let%bind` now requires three functions instead of two. It would also naturally give a translation of:

```ocaml
join (apply (pure (fun P1 -> E)) x1))
```

in the single `let%bind` case which is undesirable.

Whereas using the multiplicative operation from the monoidal presentation of applicative -- i.e. `both` -- you get:

```ocaml
let x1 = M1 and x2 = M2 and x3 = M3 and x4 = M4 in
bind (both x1 (both x2 (both x3 x4)))
  (fun (P1, (P2, (P3, P4))) -> E)
```

for `let%bind` and:


```ocaml
let x1 = M1 and x2 = M2 and x3 = M3 and x4 = M4 in
map (both x1 (both x2 (both x3 x4)))
  (fun (P1, (P2, (P3, P4))) -> E)
```

for `let%map`. Here the translations only differ in the use of `bind` or `map` and they naturally degrade to the expected code for the single `bind` and `map` cases.

Using `both` also tends to allocate less for intermediate structures than using `apply` because tuples are smaller than closures. Although that depends on how exactly you implement them, but if you try to optimise the definitions of both of them you will generally find that the `both` version is cheaper by a constant factor.

I also have a general preference for the monoidal presentation of applicatives -- the laws are simpler and the whole thing seems like a clearer presentation of what an applicative is to me -- but that's just a matter of taste. See section 7 of the original applicative functors paper ("Applicative Programming with Effects" by McBride and Paterson) for a description of the monoidal presentation.

**Comment by texastoland** [comment]
@lpw25 I'll look for the effects paper. I love what you're doing with OCaml in general. I rewatched [your effects talk](https://twitter.com/texastoland/status/1014550271412854784) multiple times. Thank you for sharing!!
